version: "3.8"
services:
    risk-db:
        container_name: risk-db
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'admin'
            MYSQL_DATABASE: 'risk'
        volumes:
          - type: bind
            source: ./migrations
            target: /docker-entrypoint-initdb.d
        ports:
            - 8765:3306
